#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    parallelism: 4
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup permission
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Unit Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex test
      - run:
          name: Install custom system image
          command: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb
      - run:
          name: Setup emulator
          command: echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb
      - run:
          name: Launch emulator
          command: emulator -avd testEmulator -no-audio -no-window
          background: false
          no_output_timeout: 20m
      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb
      - run:
          name: Run Instrumented Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex connectedAndroidTest
          environment:
            TERM: dumb
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
