#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: Run Unit Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex test
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-26;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-23;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Run Instrumented Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex connectedAndroidTest