#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    parallelism: 4
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup permission
          command: chmod +x gradlew
      - run:
          name: Android SDK Platform 26
          command: if [ ! -d "/usr/local/android-sdk-linux/platforms/android-26" ]; then echo y | android update sdk --no-ui --all --filter "android-26"; fi
          environment:
            TERM: dumb
      - run:
          name: Android SDK Build-tools
          command: if [ ! -d "/usr/local/android-sdk-linux/build-tools/26.0.2" ]; then echo y | android update sdk --no-ui --all --filter "build-tools-26.0.2"; fi
          environment:
            TERM: dumb
      - run:
          name: Android Support Repository
          command: if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/26.1.0" ]; then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
          environment:
            TERM: dumb
      - run:
          name: Install Android SDK platforms API Level 26 
          command: $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-26"
          environment:
            TERM: dumb
      - run:
          name: Install Android SDK platform-tools 
          command: $ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
          environment:
            TERM: dumb
      - run:
          name: Install Android SDK build tools
          command: $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.2"
          environment:
            TERM: dumb
      - run:
          name: Accept Android Licenses
          command: mkdir -p "/opt/android/sdk/licenses" && echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "/opt/android/sdk/licenses/android-sdk-license" && echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "/opt/android/sdk/licenses/android-sdk-preview-license" 
          environment:
            TERM: dumb
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          environment:
            TERM: dumb
      - run:
          name: Run Unit Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex test
          environment:
            TERM: dumb
      - run:
          name: Install custom system image
          command: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb
      - run:
          name: Setup emulator
          command: echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb
      - run:
          name: Launch emulator
          command: emulator -avd testEmulator -no-audio -no-window
          background: false
          no_output_timeout: 20m
      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb
      - run:
          name: Run Instrumented Tests
          command: ./gradlew --configure-on-demand -PdisablePreDex connectedAndroidTest
          environment:
            TERM: dumb
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
